[package]
name = "flate2-miniz_oxide"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
common = { path = "../../common" }
flate2 = { version = "1.0.26", default-features = false, features = ["rust_backend"] }
