[package]
name = "lz4_flex"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
common = { path = "../../common" }
lz4_flex = { version = "0.10.0", default-features = false, features = ["std"] }
